### ISSUE TITLE
I can't download whatsapp status for my gallery

### ISSUE THREAD

**Issue by Bithusha1** [netharuM/whatskit#2]
![Screenshot_20220424-221728](https://user-images.githubusercontent.com/104317475/164987179-05dcf339-03d4-4cf7-8fcc-35aa0481e020.jpg)

I have save it too many times, but it doesn't visible in gallery. Please fix it👍

**Comment by netharuM** [comment]
currently, we have no idea what is the cause of this issue
but we will look forward to fixing it 

thanks for the report

**Comment by netharuM** [comment]
![image](https://user-images.githubusercontent.com/60318339/165205683-bfda0214-2763-47db-a4ac-88ea836ac93b.png)

I copied the file manually (with the file manager) to the DCIM folder and it started to appear in the gallery
but when I do it with the CLI ```cp``` command
it doesn't show up 

as you can see both files look the same
screenshot contains the file that I have copied with the "file manager"

**Comment by netharuM** [comment]
we have fixed the issue in the latest release [v1.0.3+7](../releases/tag/v1.0.3+7)

we`ve added an option to select between "gallery" and "folder" when you are saving the status


![image](https://user-images.githubusercontent.com/60318339/165400072-33ce86c9-e172-4eca-ba11-e2bfb6cc6e2f.png)
